//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.12 at 01:12:56 PM MSK 
//


package by.foranx.webservice.entity;

import by.foranx.webservice.repository.ErrorsRepository;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Payment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payment"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AnsAuthPay"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AdditionInfo" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="PNameID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="PValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payment", propOrder = {
    "ansAuthPay"
})
public class Payment {

    @XmlElement(name = "AnsAuthPay", required = true)
    protected AnsAuthPay ansAuthPay;

    /**
     * Gets the value of the ansAuthPay property.
     * 
     * @return
     *     possible object is
     *     {@link AnsAuthPay }
     *     
     */
    public AnsAuthPay getAnsAuthPay() {
        return ansAuthPay;
    }

    /**
     * Sets the value of the ansAuthPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnsAuthPay }
     *     
     */
    public void setAnsAuthPay(AnsAuthPay value) {
        this.ansAuthPay = value;
    }

    public Response validate() {
        ErrorsRepository errorsRepository = new ErrorsRepository();
        try {
            List<Payment.AnsAuthPay.AdditionInfo> additionInfos = new ArrayList<>(this.getAnsAuthPay().getAdditionInfo());
            if (additionInfos.size() < 4) return errorsRepository.findError(5);

            for (Payment.AnsAuthPay.AdditionInfo info : additionInfos) {
                switch (info.getPNameID()) {
                    case "RcvFio0":
                        if (info.getPValue() == null || info.getPValue().isBlank())
                            return errorsRepository.findError(1);
                        break;
                    case "RcvAddress0":
                        if (info.getPValue() == null || info.getPValue().isBlank())
                            return errorsRepository.findError(2);
                        break;
                    case "RcvIban0":
                        if (info.getPValue() == null || info.getPValue().isBlank())
                            return errorsRepository.findError(3);
                        if (!info.getPValue().startsWith("KZ"))
                            return errorsRepository.findError(8);
                        break;
                    case "Cur0":
                        if (info.getPValue() == null || info.getPValue().isBlank())
                            return errorsRepository.findError(4);
                        break;
                    default:
                        return errorsRepository.findError(6);
                }
            }
            return errorsRepository.findError(0);
        }
        catch (Exception e) {
            return errorsRepository.findError(7);
        }
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AdditionInfo" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="PNameID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="PValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "additionInfo"
    })
    public static class AnsAuthPay {

        @XmlElement(name = "AdditionInfo", required = true)
        protected List<AdditionInfo> additionInfo;

        /**
         * Gets the value of the additionInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the additionInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdditionInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AdditionInfo }
         * 
         * 
         */
        public List<AdditionInfo> getAdditionInfo() {
            if (additionInfo == null) {
                additionInfo = new ArrayList<AdditionInfo>();
            }
            return this.additionInfo;
        }

        /**
         * Sets the value of the additionInfo property.
         */

        public void setAdditionInfo(List<AdditionInfo> value) {
            this.additionInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="PNameID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="PValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pNameID",
            "pValue"
        })
        public static class AdditionInfo {

            @XmlElement(name = "PNameID", required = true)
            protected String pNameID;
            @XmlElement(name = "PValue", required = true)
            protected String pValue;

            /**
             * Gets the value of the pNameID property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPNameID() {
                return pNameID;
            }

            /**
             * Sets the value of the pNameID property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPNameID(String value) {
                this.pNameID = value;
            }

            /**
             * Gets the value of the pValue property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPValue() {
                return pValue;
            }

            /**
             * Sets the value of the pValue property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPValue(String value) {
                if (this.pNameID.equals("RcvIban0"))
                    assert value.matches("^KZ.*") : "IBAN must starts with KZ!";
                this.pValue = value;
            }
        }
    }
}
